name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-85.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  flutter_svg: ^1.1.6
  lottie: ^2.1.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SFpro
      fonts:
        - asset: assets/fonts/font.OTF

    - family: AbeeZee
      fonts:
        - asset: assets/fonts/ABeeZee_font.ttf
